name: toledotechevents
description: An Android, iOS, and web app version of http://toledotechevents.org.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/toledotechevents

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  rxdart: ^0.18.1
  json_serializable: ^0.5.8+1
  json_annotation: ^0.2.9+1
  http: ^0.11.3+17
  english_words: ^3.1.0
  crypto: ^2.0.3
  xml: ^3.0.0
  html: ^0.13.3
  html_unescape: ^1.0.0
  intl: any
  meta: any

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0