name: toledotechevents_mobile
description: ToledoTechEvents.org's companion app.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0


  flutter_html_view: ^0.4.0

  url_launcher: ^3.0.1
  datetime_picker_formfield: ^0.1.1
  simple_autocomplete_formfield: ^0.1.1
  network_resource: ^0.2.4
  toledotechevents:
    path: ../toledotechevents


dev_dependencies:
  flutter_test:
    sdk: flutter

# environment:
#   sdk: ">=1.20.1 <3.0.0"
#   flutter: ">=0.1.2 <2.0.0"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: ../fonts/Ubuntu-Regular.ttf
        - asset: ../fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: ../fonts/Ubuntu-Light.ttf
          weight: 300
    - family: Open Sans
      fonts:
        - asset: ../fonts/OpenSans-Regular.ttf
        - asset: ../fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: ../fonts/OpenSans-Italic.ttf
          style: italic
        - asset: ../fonts/OpenSans-Light.ttf
          weight: 300
        - asset: ../fonts/OpenSans-SemiBold.ttf
          weight: 500
