name: toledotechevents_web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Jacob Phillips <email@example.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
#  toledotechevents:
#    path: ../toledotechevents
  pwa: ^0.1.10

dev_dependencies:
  angular_test: ^2.0.0-beta
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
