name: toledotechevents
description: An Android, iOS, and web app version of http://toledotechevents.org.
version: 0.0.1
author: Jacob Phillips <jifalops@gmail.com>
homepage: https://github.com/jifalops/toledotechevents

environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dependencies:
  rxdart: ^0.18.1
  http: ^0.11.3+16
  english_words: ^3.1.0
  crypto: ^2.0.3
  xml: ^3.0.0
  html: ^0.13.3
  html_unescape: ^1.0.0
  intl: any
  meta: any
  async_resource: ^0.1.2
  display: ^0.0.2
  abstract_theme:
    path: ../../abstract_theme




dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  collection: ^1.14.11