name: toledotechevents_web
description: A web app that uses AngularDart Components
version: 1.0.0
homepage: https://www.example.com
author: Jacob Phillips <email@example.com>

environment:
  sdk: '>=2.0.0-dev.69.5 <3.0.0'

dependencies:
  angular: ^5.0.0-beta
  angular_components: ^0.9.0-beta
  bootstrap_sass: ^4.1.2
  toledotechevents:
    path: ../base
  pwa:
    git: https://github.com/jifalops/pwa

dev_dependencies:
  angular_test: ^2.0.0-beta
  sass_builder: ^2.0.0
  build_runner: ^0.9.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
